install:
  git:
    sdk_ref: b-8.0.x
  method: 'script'
  container:
    options: '-e ESHOP_BOOTSTRAP_PATH=vendor/oxid-esales/oxideshop-ce/source/bootstrap.php'
  composer:
    root_url: 'https://raw.githubusercontent.com/{{ .Github.Repository }}/b-8.0/composer.json'
    transform: |
      {
        "config": {
          "github-protocols": ["https"],
          "allow-plugins":{
            "oxid-esales/oxideshop-composer-plugin":true,
            "oxid-esales/oxideshop-unified-namespace-generator":true
          }
        },
        "minimum-stability": "dev",
        "prefer-stable": true,
        "preferred-install": {
          "oxid-esales/*": "source",
          "oxid-professional-services/*": "source",
          "ddoe/*": "source",
          "makaira/*": "source"
        },
        "require-dev":{
          "oxid-esales/codeception-modules":"{{ .Data.global.composer.dev_ref }}",
          "oxid-esales/codeception-page-objects":"{{ .Data.global.composer.dev_ref }}",
          "oxid-esales/developer-tools":"{{ .Data.global.composer.dev_ref }}",
          "oxid-esales/oxideshop-ide-helper":"{{ .Data.global.composer.dev_ref }}",
          "codeception/codeception":"^5.0",
          "codeception/module-asserts":"^3.0",
          "codeception/module-db":"^3.0",
          "codeception/module-filesystem":"^3.0",
          "codeception/module-webdriver":"^4.0",
          "incenteev/composer-parameter-handler":"^v2.1.4",
          "mikey179/vfsstream":"~1.6.8",
          "phpspec/prophecy-phpunit":"^v2.0.1",
          "phpunit/phpunit":"^11.4",
          "squizlabs/php_codesniffer":"^3.5.4",
          "symfony/browser-kit": "^6.4",
          "symfony/http-client": "^6.4"
        },
        "autoload-dev":{
          "psr-4":{
            "OxidEsales\\EshopCommunity\\Tests\\":"./vendor/oxid-esales/oxideshop-ce/tests"
          }
        }
      }
  activate_modules: ''

runscript:
  matrix:
    script: |
      [
        "shop:~/unit.sh",
        "shop:~/integration.sh",
        "shop:~/codeception.sh Acceptance 1 4",
        "shop:~/codeception.sh Acceptance 2 4",
        "shop:~/codeception.sh Acceptance 3 4",
        "shop:~/codeception.sh Acceptance 4 4"
      ]
  composer:
    early: skip
  workdir: ''
  shop:
    path: 'vendor/oxid-esales/oxideshop-ce'
    workdir: 'vendor/oxid-esales/oxideshop-ce'
    container:
      options: >
        -e XDEBUG_MODE=coverage
        -e THEME_ID=apex
        -e MODULE_IDS=eyeable_assist,makaira_oxid-connect-essential,oxps_usercentrics,oegdproptin,ddoemedialibrary,ddoewysiwyg
        -e SELENIUM_SERVER_HOST=selenium
        -e BROWSER_NAME=chrome
        -e TEST_SUITE=/var/www/vendor/oxid-esales/oxideshop-ce/tests
        -e INTEGRATION_OPTIONS="--exclude-group exclude_from_compilation --exclude-group exclude-from-compilation" \

sonarcloud:
  matrix:
    testplan: 'skip'

finish:
  slack_title: 'Metapackage CE (8.0 slim) on {{ .Github.Repository }} by {{ .Github.Actor }}'
