install:
  method: 'script'
  copy_script_targets: |
    vendor/oxid-esales/oxideshop-ce/tests/scripts
    vendor/oxid-esales/gdpr-optin-module/tests/scripts
    vendor/oxid-professional-services/usercentrics/tests/scripts
    vendor/makaira/oxid-connect-essential/tests/scripts
    vendor/ddoe/wysiwyg-editor-module/tests/scripts
    vendor/oxid-esales/media-library-module/tests/scripts
  container:
    options: '-e ESHOP_BOOTSTRAP_PATH=vendor/oxid-esales/oxideshop-ce/source/bootstrap.php'
  composer:
    root_url: 'https://raw.githubusercontent.com/{{ .Github.Repository }}/b-7.0/composer.json'
    transform: |
      {
          "config": {
              "github-protocols": ["https"],
              "allow-plugins":{
                "oxid-esales/oxideshop-composer-plugin":true,
                "oxid-esales/oxideshop-unified-namespace-generator":true
              }
          },
          "preferred-install": {
            "oxid-esales/*": "source",
            "oxid-professional-services/*": "source",
            "ddoe/*": "source",
            "makaira/*": "source"
          },
          "require": {
            "oxid-esales/developer-tools": "{{ .Data.global.composer.dev_ref }}",
            "composer/composer": "^2.0",
            "twig/twig": "v3.8.0"
          },
          "require-dev":{
              "oxid-esales/codeception-modules":"{{ .Data.global.composer.dev_ref }}",
              "oxid-esales/codeception-page-objects":"{{ .Data.global.composer.dev_ref }}",
              "oxid-esales/developer-tools":"{{ .Data.global.composer.dev_ref }}",
              "oxid-esales/oxideshop-ide-helper":"{{ .Data.global.composer.dev_ref }}",
              "codeception/codeception": "^5.0",
              "codeception/module-asserts": "^3.0",
              "codeception/module-db": "^3.0",
              "codeception/module-filesystem": "^3.0",
              "codeception/module-webdriver": "^3.1",
              "composer/composer": "^2.0",
              "incenteev/composer-parameter-handler": "^v2.1.4",
              "mikey179/vfsstream": "~1.6.8",
              "phpspec/prophecy-phpunit": "^v2.0.1",
              "phpunit/phpunit": "^9.1.1",
              "phpstan/phpstan": "^1.9.14",
              "squizlabs/php_codesniffer": "^3.5.4"
          },
          "autoload-dev":{
              "psr-4":{
                "OxidEsales\\EshopCommunity\\Tests\\":"./vendor/oxid-esales/oxideshop-ce/tests",
                "OxidEsales\\ComposerPlugin\\Tests\\": "vendor/oxid-esales/oxideshop-composer-plugin/tests/",
                "OxidEsales\\UnifiedNameSpaceGenerator\\Tests\\": "./vendor/oxid-esales/oxideshop-unified-namespace-generator/tests",
                "OxidEsales\\DemoDataInstaller\\Tests\\": "./vendor/oxid-esales/oxideshop-demodata-installer/tests/",
                "OxidEsales\\DoctrineMigrationWrapper\\Tests\\": "./vendor/oxid-esales/oxideshop-doctrine-migration-wrapper/tests",
                "OxidEsales\\Facts\\Tests\\": "./vendor/oxid-esales/oxideshop-facts/tests/",
                "OxidEsales\\Twig\\Tests\\": "./vendor/oxid-esales/twig-component/tests",
                "OxidEsales\\GdprOptinModule\\Tests\\": "./vendor/oxid-esales/gdpr-optin-module/tests/",
                "OxidProfessionalServices\\Usercentrics\\Tests\\": "./vendor/oxid-professional-services/usercentrics/tests"
              }
          },
          "bin":[
              "bin/oe-console"
          ]
      }
  activate_modules: |
    oegdproptin
    oxps_usercentrics
    makaira_oxid-connect-essential
    ddoemedialibrary
    ddoewysiwyg
  custom_script_container: |
    # Activate all modules
    if [ -f 'bin/oe-console' ]; then
        OE_CONSOLE='bin/oe-console'
    else
        if [ -f 'vendor/bin/oe-console' ]; then
        OE_CONSOLE='vendor/bin/oe-console'
        else
            error "Can't find oe-console in bin or vendor/bin!"
        fi
    fi
    ${OE_CONSOLE} oe:setup:demodata

runscript: &runscript
  matrix:
    script: |
      [
        "shop:~/unit.sh",
        "shop:~/integration.sh",
        "shop:~/codeception.sh",
        "gdpr:~/unit.sh",
        "gdpr:~/integration.sh",
        "gdpr:~/codeception.sh",
        "usercentrics:~/unit.sh",
        "usercentrics:~/integration.sh",
        "usercentrics:~/codeception.sh acceptance",
        "ddoe_wysiwyg_codeception_twig:~/codeception.sh acceptance"      ]
  container:
    # {{ $selenium_options := "-e SELENIUM_SERVER_HOST=selenium -e BROWSER_NAME=chrome" }}
    # {{ $module_ids := "-e MODULE_IDS=oegdproptin,oxps_usercentrics,makaira_oxid-connect-essential,ddoewysiwyg" }}
    options: '-e XDEBUG_MODE=coverage -e THEME_ID=apex {{ $selenium_options }} {{ $module_ids }}'
  composer:
    early: skip
  workdir: ''
  shop:
    path: 'vendor/oxid-esales/oxideshop-ce'
    workdir: 'vendor/oxid-esales/oxideshop-ce'
  gdpr:
    path: 'vendor/oxid-esales/gdpr-optin-module'
    custom_script: |
     perl -pi \
          -e 's#views/twig#views/apex#g;' \
          source/vendor/oxid-esales/gdpr-optin-module/tests/Codeception/acceptance.suite.yml
  usercentrics:
    path: 'vendor/oxid-professional-services/usercentrics'
    container:
  makaira:
    path: 'vendor/makaira/oxid-connect-essential'
  ddoe_wysiwyg:
    path: 'vendor/ddoe/wysiwyg-editor-module'
  ddoe_wysiwyg_codeception_twig:
    path: 'vendor/ddoe/wysiwyg-editor-module'
    container:
      # yamllint disable-line rule:line-length
      options: '-e XDEBUG_MODE=coverage -e THEME_ID=twig {{ $selenium_options }} {{ $module_ids }}'
    composer:
      transform: |
        {
            "require":     {
                "oxid-esales/twig-theme": "dev-b-7.0.x"
            },
              "require-dev": {
                  "oxid-esales/oxideshop-facts":"{{ .Data.global.composer.dev_ref }}",
                  "oxid-esales/codeception-modules":"{{ .Data.global.composer.dev_ref }}",
                  "oxid-esales/codeception-page-objects":"{{ .Data.global.composer.dev_ref }}",
                  "codeception/codeception": "^5.0",
                  "codeception/module-asserts": "^3.0",
                  "codeception/module-db": "^3.0",
                  "codeception/module-filesystem": "^3.0",
                  "codeception/module-webdriver": "^3.1",
                  "phpunit/phpunit": "^9.1.1"
              },
              "autoload-dev":{
                  "psr-4":{
                    "OxidEsales\\EshopCommunity\\Tests\\":"./vendor/oxid-esales/oxideshop-ce/tests",
                    "OxidEsales\\ComposerPlugin\\Tests\\": "vendor/oxid-esales/oxideshop-composer-plugin/tests/",
                    "OxidEsales\\UnifiedNameSpaceGenerator\\Tests\\": "./vendor/oxid-esales/oxideshop-unified-namespace-generator/tests",
                    "OxidEsales\\DemoDataInstaller\\Tests\\": "./vendor/oxid-esales/oxideshop-demodata-installer/tests/",
                    "OxidEsales\\DoctrineMigrationWrapper\\Tests\\": "./vendor/oxid-esales/oxideshop-doctrine-migration-wrapper/tests",
                    "OxidEsales\\Facts\\Tests\\": "./vendor/oxid-esales/oxideshop-facts/tests/",
                    "OxidEsales\\Twig\\Tests\\": "./vendor/oxid-esales/twig-component/tests",
                    "OxidEsales\\GdprOptinModule\\Tests\\": "./vendor/oxid-esales/gdpr-optin-module/tests/",
                    "OxidProfessionalServices\\Usercentrics\\Tests\\": "./vendor/oxid-professional-services/usercentrics/tests"
                  }
              }
          }
  medialibrary:
    path: 'vendor/oxid-esales/media-library-module'

sonarcloud:
  matrix:
    testplan: 'skip'

finish:
  slack_title: 'Metapackage CE (7.0 slim) on {{ .Github.Repository }} by {{ .Github.Actor }}'
