install:
  method: 'script'
  container:
    options: '-e ESHOP_BOOTSTRAP_PATH=vendor/oxid-esales/oxideshop-ce/source/bootstrap.php'
  composer:
    root_url: 'https://raw.githubusercontent.com/{{ .Github.Repository }}/b-7.0/composer.json'
    transform: |
      {
          "config": {
              "github-protocols": ["https"],
              "allow-plugins":{
                "oxid-esales/oxideshop-composer-plugin":true,
                "oxid-esales/oxideshop-unified-namespace-generator":true
              }
          },
          "preferred-install": {
            "oxid-esales/*": "source",
            "oxid-professional-services/*": "source",
            "ddoe/*": "source",
            "makaira/*": "source"
          },
          "require": {
            "oxid-esales/developer-tools": "{{ .Data.global.composer.dev_ref }}",
            "composer/composer": "^2.0",
            "twig/twig": "v3.8.0"
          },
          "require-dev":{
              "oxid-esales/codeception-modules":"{{ .Data.global.composer.dev_ref }}",
              "oxid-esales/codeception-page-objects":"{{ .Data.global.composer.dev_ref }}",
              "oxid-esales/developer-tools":"{{ .Data.global.composer.dev_ref }}",
              "oxid-esales/oxideshop-ide-helper":"{{ .Data.global.composer.dev_ref }}",
              "codeception/codeception": "^5.0",
              "codeception/module-asserts": "^3.0",
              "codeception/module-db": "^3.0",
              "codeception/module-filesystem": "^3.0",
              "codeception/module-webdriver": "^3.1",
              "composer/composer": "^2.0",
              "incenteev/composer-parameter-handler": "^v2.1.4",
              "mikey179/vfsstream": "~1.6.8",
              "phpspec/prophecy-phpunit": "^v2.0.1",
              "phpunit/phpunit": "^9.1.1",
              "phpstan/phpstan": "^1.9.14",
              "squizlabs/php_codesniffer": "^3.5.4"
          },
          "repositories": {
            "oxid-esales/oxideshop-ce": {
              "type": "git",
              "url": "https://github.com/OXID-eSales/oxideshop_ce.git"
            },
            "oxid-esales/gdpr-optin-module": {
              "type": "git",
              "url": "https://github.com/OXID-eSales/gdpr-optin-module.git"
            },
            "oxid-esales/oxideshop-composer-plugin": {
              "type": "git",
              "url": "https://github.com/OXID-eSales/oxideshop_composer_plugin.git"
            },
            "oxid-esales/oxideshop-doctrine-migration-wrapper": {
              "type": "git",
              "url": "https://github.com/OXID-eSales/oxideshop-doctrine-migration-wrapper.git"
            },
            "oxid-esales/oxideshop-facts": {
              "type": "git",
              "url": "https://github.com/OXID-eSales/oxideshop-facts.git"
            },
            "oxid-esales/oxideshop-unified-namespace-generator": {
              "type": "git",
              "url": "https://github.com/OXID-eSales/oxideshop-unified-namespace-generator.git"
            },
            "oxid-esales/twig-component": {
              "type": "git",
              "url": "https://github.com/OXID-eSales/twig-component.git"
            },
            "oxid-professional-services/usercentrics": {
              "type": "git",
              "url": "https://github.com/OXID-eSales/usercentrics.git"
            },
            "makaira/oxid-connect-essential": {
              "type": "git",
              "url": "https://github.com/MakairaIO/oxid-connect-essential.git"
            }
          },
          "autoload-dev":{
              "psr-4":{
                "OxidEsales\\EshopCommunity\\Tests\\":"./vendor/oxid-esales/oxideshop-ce/tests",
                "OxidEsales\\ComposerPlugin\\Tests\\": "vendor/oxid-esales/oxideshop-composer-plugin/tests/",
                "OxidEsales\\UnifiedNameSpaceGenerator\\Tests\\": "./vendor/oxid-esales/oxideshop-unified-namespace-generator/tests",
                "OxidEsales\\DemoDataInstaller\\Tests\\": "./vendor/oxid-esales/oxideshop-demodata-installer/tests/",
                "OxidEsales\\DoctrineMigrationWrapper\\Tests\\": "./vendor/oxid-esales/oxideshop-doctrine-migration-wrapper/tests",
                "OxidEsales\\Facts\\Tests\\": "./vendor/oxid-esales/oxideshop-facts/tests/",
                "OxidEsales\\Twig\\Tests\\": "./vendor/oxid-esales/twig-component/tests",
                "OxidEsales\\GdprOptinModule\\Tests\\": "./vendor/oxid-esales/gdpr-optin-module/tests/",
                "OxidProfessionalServices\\Usercentrics\\Tests\\": "./vendor/oxid-professional-services/usercentrics/tests"
              }
          },
          "bin":[
              "bin/oe-console"
          ]
      }
  activate_modules: |
    oegdproptin
    oxps_usercentrics
    makaira_oxid-connect-essential
    ddoemedialibrary
    ddoewysiwyg
  custom_script: |
    # Copy test scripts for components/modules that are not yet using them
    for MODULE in oxid-esales/gdpr-optin-module oxid-esales/oxideshop-composer-plugin oxid-esales/oxideshop-demodata-installer \
                  oxid-esales/oxideshop-doctrine-migration-wrapper oxid-esales/oxideshop-facts oxid-esales/twig-component \
                  oxid-esales/oxideshop-unified-namespace-generator oxid-professional-services/usercentrics \
                  makaira/oxid-connect-essential ddoe/wysiwyg-editor-module
    do
      mkdir -p "source/vendor/${MODULE}/tests/scripts"
      for FILE in $(find .github/oxid-esales/defaults/scripts -iname "*.sh" -o -iname "*.txt"); do
        BASE=$(basename "${FILE}")
        if [ -f "source/vendor/${MODULE}/tests/scripts/${BASE}" ]; then
          echo "File 'source/vendor/${MODULE}/tests/scripts/${BASE}' already exists, skipping copy"
        else
          echo "Copying default file '${FILE}' to 'source/vendor/${MODULE}/tests/scripts/'"
          cp -a "${FILE}" "source/vendor/${MODULE}/tests/scripts/${BASE}"
        fi
      done
      if [ ! -f "source/vendor/${MODULE}/tests/phpunit.xml" ]; then
        echo -e "\033[0;35mcopying generic phpunit9.xml to 'source/vendor/${MODULE}/tests/phpunit.xml'\033[0m"
        cp ".github/oxid-esales/defaults/scripts/phpunit9.xml" "source/vendor/${MODULE}/tests/phpunit.xml"
      fi
    done
  custom_script_container: |
    # Activate all modules
    if [ -f 'bin/oe-console' ]; then
        OE_CONSOLE='bin/oe-console'
    else
        if [ -f 'vendor/bin/oe-console' ]; then
        OE_CONSOLE='vendor/bin/oe-console'
        else
            error "Can't find oe-console in bin or vendor/bin!"
        fi
    fi
    # mkdir -p /var/www/vendor/oxid-esales/oxideshop-ce/vendor/oxid-esales
    # ln -s /var/www/vendor/oxid-esales/oxideshop-demodata-ce /var/www/vendor/oxid-esales/oxideshop-ce/vendor/oxid-esales/oxideshop-demodata-ce^
    # cp /var/www/vendor/oxid-esales/oxideshop-ce/source/config.inc.php /var/www/source/config.inc.php
    # cp /var/www/vendor/oxid-esales/oxideshop-ce/source/config.inc.php /var/www/vendor/oxid-esales/gdpr-optin-module/source/config.inc.php
    ${OE_CONSOLE} oe:setup:demodata

runscript: &runscript
  matrix:
    script: |
      [
        "shop:~/unit.sh",
        "shop:~/integration.sh",
        "shop:~/codeception.sh",
        "facts:~/unit.sh",
        "gdpr:~/unit.sh",
        "gdpr:~/integration.sh",
        "gdpr:~/codeception.sh",
        "composer_plugin:~/unit.sh",
        "composer_plugin:~/integration.sh",
        "ddinst:~/unit.sh",
        "ddinst:~/integration.sh",
        "doctrine:~/unit.sh",
        "doctrine:~/integration.sh",
        "ung:~/integration.sh",
        "twig:~/unit.sh",
        "twig:~/integration.sh",
        "usercentrics:~/unit.sh",
        "usercentrics:~/integration.sh",
        "usercentrics:~/codeception.sh acceptance",
        "makaira:~/unit.sh",
        "makaira:~/integration.sh",
        "ddoe_wysiwyg_codeception_twig:~/codeception.sh acceptance"
      ]
  container:
    # yamllint disable-line rule:line-length
    options: '-e THEME_ID=apex -e MODULE_IDS=oegdproptin,oxps_usercentrics,makaira_oxid-connect-essential,ddoewysiwyg -e ESHOP_BOOTSTRAP_PATH=vendor/oxid-esales/oxideshop-ce/source/bootstrap.php -e SELENIUM_SERVER_HOST=selenium -e BROWSER_NAME=chrome'
  composer:
    early: skip
  workdir: ''
  shop: &shop
    path: 'vendor/oxid-esales/oxideshop-ce'
    workdir: 'vendor/oxid-esales/oxideshop-ce'
    container:
      # yamllint disable-line rule:line-length
      options: '-e XDEBUG_MODE=coverage -e GITHUB_EVENT_NAME={{ .Github.EventName }} -e GITHUB_BASE_REF={{ .Github.BaseRef }} -e GITHUB_REF={{ .Github.Ref }} -e GITHUB_REF_NAME={{ .Github.RefName }} -e THEME_ID=apex -e TEST_SUITE=/var/www/vendor/oxid-esales/oxideshop-ce/tests -e MODULE_IDS=oegdproptin,oxps_usercentrics,makaira_oxid-connect-essential,ddoewysiwyg -e SELENIUM_SERVER_HOST=selenium -e BROWSER_NAME=chrome'
  facts:
    path: 'vendor/oxid-esales/oxideshop-facts'
    composer:
      early: skip
    container:
      # yamllint disable-line rule:line-length
      options: '-e SUITE=vendor/oxid-esales/oxideshop-facts/tests -e XDEBUG_MODE=coverage -e GITHUB_EVENT_NAME={{ .Github.EventName }} -e GITHUB_BASE_REF={{ .Github.BaseRef }} -e GITHUB_REF={{ .Github.Ref }} -e GITHUB_REF_NAME={{ .Github.RefName }} -e THEME_ID=apex -e TEST_SUITE=/var/www/vendor/oxid-esales/oxideshop-ce/tests -e MODULE_IDS=oegdproptin,oxps_usercentrics,makaira_oxid-connect-essential,ddoewysiwyg -e SELENIUM_SERVER_HOST=selenium -e BROWSER_NAME=chrome'
  gdpr:
    path: 'vendor/oxid-esales/gdpr-optin-module'
    custom_script: |
     perl -pi \
          -e 's#views/twig#views/apex#g;' \
          source/vendor/oxid-esales/gdpr-optin-module/tests/Codeception/acceptance.suite.yml
  composer_plugin:
    path: 'vendor/oxid-esales/oxideshop-composer-plugin'
    composer:
      early: skip
  ddinst:
    path: 'vendor/oxid-esales/oxideshop-demodata-installer'
    # custom_script_container: |
    #   cd vendor/oxid-esales/oxideshop-demodata-installer
    #   sed -e 's|tests/Unit|tests/Unit/Framework/Module/Demodata|' -i tests/scripts/unit.sh
    #   sed -e 's|tests/Integration|tests/Integration/Framework/Module/Demodata|' -i tests/scripts/integration.sh
    #   cat tests/scripts/unit.sh
  doctrine:
    path: 'vendor/oxid-esales/oxideshop-doctrine-migration-wrapper'
  ung:
    path: 'vendor/oxid-esales/oxideshop-unified-namespace-generator'
  twig:
    path: 'vendor/oxid-esales/twig-component'
    workdir: '~'
    #custom_script: |
    #  cp -a .github/oxid-esales/defaults/scripts/*.sh source/vendor/oxid-esales/twig-component/tests/scripts/
  usercentrics:
    path: 'vendor/oxid-professional-services/usercentrics'
    container:
      # yamllint disable-line rule:line-length
      options: '-e XDEBUG_MODE=coverage -e GITHUB_EVENT_NAME={{ .Github.EventName }} -e GITHUB_BASE_REF={{ .Github.BaseRef }} -e GITHUB_REF={{ .Github.Ref }} -e GITHUB_REF_NAME={{ .Github.RefName }} -e THEME_ID=apex -e MODULE_IDS=oegdproptin,oxps_usercentrics,makaira_oxid-connect-essential,ddoewysiwyg -e SELENIUM_SERVER_HOST=selenium -e BROWSER_NAME=chrome'
    # custom_script: |
    #   mkdir -p source/vendor/oxid-professional-services/usercentrics/source
    #   cp source/source/config.inc.php source/vendor/oxid-professional-services/usercentrics/source/config.inc.php
    # custom_script_container: |
    #   cd vendor/oxid-professional-services/usercentrics
    #   sed -e 's|BOOTSTRAP="../oxideshop-ce/tests|BOOTSTRAP="../../oxid-esales/oxideshop-ce/tests|' \
    #       -i tests/scripts/unit.sh
    #   sed -e 's|BOOTSTRAP="../oxideshop-ce/tests|BOOTSTRAP="../../oxid-esales/oxideshop-ce/tests|' \
    #       -i tests/scripts/integration.sh
  makaira:
    path: 'vendor/makaira/oxid-connect-essential'
    # custom_script_container: |
    #   cd vendor/makaira/oxid-connect-essential
    #   sed -e 's|BOOTSTRAP="../oxideshop-ce/tests|BOOTSTRAP="../../oxid-esales/oxideshop-ce/tests|' \
    #       -i tests/scripts/unit.sh
    #   sed -e 's|BOOTSTRAP="../oxideshop-ce/tests|BOOTSTRAP="../../oxid-esales/oxideshop-ce/tests|' \
    #       -i tests/scripts/integration.sh
  ddoe_wysiwyg:
    path: 'vendor/ddoe/wysiwyg-editor-module'
    # custom_script_container: |
    #   cd vendor/ddoe/wysiwyg-editor-module
    #   sed -e 's|BOOTSTRAP="../oxideshop-ce/tests|BOOTSTRAP="../../oxid-esales/oxideshop-ce/tests|' \
    #       -i tests/scripts/unit.sh
    #   sed -e 's|BOOTSTRAP="../oxideshop-ce/tests|BOOTSTRAP="../../oxid-esales/oxideshop-ce/tests|' \
    #       -i tests/scripts/integration.sh
  ddoe_wysiwyg_codeception_twig:
    path: 'vendor/ddoe/wysiwyg-editor-module'
    container:
      # yamllint disable-line rule:line-length
      options: '-e XDEBUG_MODE=coverage -e GITHUB_EVENT_NAME={{ .Github.EventName }} -e GITHUB_BASE_REF={{ .Github.BaseRef }} -e GITHUB_REF={{ .Github.Ref }} -e GITHUB_REF_NAME={{ .Github.RefName }} -e THEME_ID=apex -e MODULE_IDS=oegdproptin,oxps_usercentrics,makaira_oxid-connect-essential,ddoewysiwyg -e SELENIUM_SERVER_HOST=selenium -e BROWSER_NAME=chrome'
    composer:
      transform: |
        {
            "require":     {
                "oxid-esales/twig-theme": "dev-b-7.0.x"
            },
              "require-dev": {
                  "oxid-esales/oxideshop-facts":"{{ .Data.global.composer.dev_ref }}",
                  "oxid-esales/codeception-modules":"{{ .Data.global.composer.dev_ref }}",
                  "oxid-esales/codeception-page-objects":"{{ .Data.global.composer.dev_ref }}",
                  "codeception/codeception": "^5.0",
                  "codeception/module-asserts": "^3.0",
                  "codeception/module-db": "^3.0",
                  "codeception/module-filesystem": "^3.0",
                  "codeception/module-webdriver": "^3.1",
                  "phpunit/phpunit": "^9.1.1"
              },
              "autoload-dev":{
                  "psr-4":{
                    "OxidEsales\\EshopCommunity\\Tests\\":"./vendor/oxid-esales/oxideshop-ce/tests",
                    "OxidEsales\\ComposerPlugin\\Tests\\": "vendor/oxid-esales/oxideshop-composer-plugin/tests/",
                    "OxidEsales\\UnifiedNameSpaceGenerator\\Tests\\": "./vendor/oxid-esales/oxideshop-unified-namespace-generator/tests",
                    "OxidEsales\\DemoDataInstaller\\Tests\\": "./vendor/oxid-esales/oxideshop-demodata-installer/tests/",
                    "OxidEsales\\DoctrineMigrationWrapper\\Tests\\": "./vendor/oxid-esales/oxideshop-doctrine-migration-wrapper/tests",
                    "OxidEsales\\Facts\\Tests\\": "./vendor/oxid-esales/oxideshop-facts/tests/",
                    "OxidEsales\\Twig\\Tests\\": "./vendor/oxid-esales/twig-component/tests",
                    "OxidEsales\\GdprOptinModule\\Tests\\": "./vendor/oxid-esales/gdpr-optin-module/tests/",
                    "OxidProfessionalServices\\Usercentrics\\Tests\\": "./vendor/oxid-professional-services/usercentrics/tests"
                  }
              }
          }
    # custom_script_container: |
    #   cd vendor/ddoe/wysiwyg-editor-module
    #   sed -e 's|BOOTSTRAP="../oxideshop-ce/tests|BOOTSTRAP="../../oxid-esales/oxideshop-ce/tests|' \
    #       -i tests/scripts/unit.sh
    #   sed -e 's|BOOTSTRAP="../oxideshop-ce/tests|BOOTSTRAP="../../oxid-esales/oxideshop-ce/tests|' \
    #       -i tests/scripts/integration.sh

runslim:
  <<: *runscript
  matrix:
    script: |
      [
        "gdpr:~/php-cs-report.sh"
      ]

sonarcloud:
  matrix:
    testplan: 'skip'

finish:
  slack_title: 'Metapackage CE (7.0 full) on {{ .Github.Repository }} by {{ .Github.Actor }}'
