install:
  copy_script_targets: |
    vendor/oxid-esales/oxideshop-ce/tests/scripts
  container:
    options: '-e ESHOP_BOOTSTRAP_PATH=vendor/oxid-esales/oxideshop-ce/source/bootstrap.php'
  composer:
    root_url: ''
    transform: |
      {
        "require-dev": {
          "codeception/codeception": "^5.0",
          "codeception/module-asserts": "^3.0",
          "codeception/module-db": "^3.0",
          "codeception/module-filesystem": "^3.0",
          "codeception/module-webdriver": "^4.0",
          "composer/composer": ">=2.0",
          "incenteev/composer-parameter-handler": "^v2.1.4",
          "mikey179/vfsstream": "~1.6.8",
          "oxid-esales/codeception-modules": "{{ .Data.global.composer.dev_ref }}",
          "oxid-esales/codeception-page-objects": "{{ .Data.global.composer.dev_ref }}",
          "oxid-esales/developer-tools": "{{ .Data.global.composer.dev_ref }}",
          "oxid-esales/oxideshop-ide-helper": "{{ .Data.global.composer.dev_ref }}",
          "phpspec/prophecy-phpunit": "^v2.0.1",
          "phpunit/phpunit":"^12.5",
          "squizlabs/php_codesniffer": "^3.5.4",
          "symfony/browser-kit": "^6.4",
          "symfony/http-client": "^6.4"
        },
        "autoload-dev": {
          "psr-4": {
            "OxidEsales\\EshopCommunity\\Tests\\":"./vendor/oxid-esales/oxideshop-ce/tests"
          }
        },
        "minimum-stability": "dev",
        "prefer-stable": true,
        "config": {
          "github-protocols": ["https"],
          "allow-plugins": {
            "oxid-esales/oxideshop-composer-plugin":true,
            "oxid-esales/oxideshop-unified-namespace-generator":true
          },
          "preferred-install": {
            "oxid-esales/*": "source"
          }
        }
      }

runscript:
  matrix:
    script: |
      [
        "ce:~/unit.sh",
        "ce:~/integration.sh",
        "ce:~/codeception.sh Acceptance 1 4",
        "ce:~/codeception.sh Acceptance 2 4",
        "ce:~/codeception.sh Acceptance 3 4",
        "ce:~/codeception.sh Acceptance 4 4",
      ]
  container:
    options:
      -e XDEBUG_MODE=coverage
      -e THEME_ID=apex
      -e SELENIUM_SERVER_HOST=selenium
      -e BROWSER_NAME=chrome
      -e CODECEPTION_OPTIONS="--ext DotReporter -x exclude_from_compilation -x exclude-from-compilation"
      -e TEST_SUITE=/var/www/vendor/oxid-esales/oxideshop-ce/tests
      -e INTEGRATION_OPTIONS="--exclude-group exclude_from_compilation --exclude-group exclude-from-compilation"
  composer:
    early: 'skip'
  coverage:
    prefix: ''
  ce:
    path: 'vendor/oxid-esales/oxideshop-ce'
    workdir: 'vendor/oxid-esales/oxideshop-ce'

sonarcloud:
  matrix:
    testplan: 'skip'

finish:
  slack_title: 'Metapackage CE (7.6 slim) on {{ .Github.Repository }} by {{ .Github.Actor }}'
