install:
  method: 'script'
  copy_script_targets: |
    vendor/oxid-esales/oxideshop-ce/tests/scripts
    vendor/oxid-esales/gdpr-optin-module/tests/scripts
    vendor/oxid-professional-services/usercentrics/tests/scripts
    vendor/makaira/oxid-connect-essential/tests/scripts
    vendor/ddoe/wysiwyg-editor-module/tests/scripts
  container:
    options: '-e ESHOP_BOOTSTRAP_PATH=vendor/oxid-esales/oxideshop-ce/source/bootstrap.php'
  composer:
    root_url: 'https://raw.githubusercontent.com/{{ .Github.Repository }}/b-7.0-release/composer.json'
    transform: |
      {
          "config": {
              "github-protocols": ["https"],
              "allow-plugins":{
                "oxid-esales/oxideshop-composer-plugin":true,
                "oxid-esales/oxideshop-unified-namespace-generator":true
              }
          },
          "require-dev":{
              "codeception/codeception": "^5.0",
              "codeception/module-asserts": "^3.0",
              "codeception/module-db": "^3.0",
              "codeception/module-filesystem": "^3.0",
              "codeception/module-webdriver": "^3.1",
              "incenteev/composer-parameter-handler": "^v2.1.4",
              "mikey179/vfsstream": "~1.6.8",
              "oxid-esales/codeception-modules": "v3.2.1",
              "oxid-esales/codeception-page-objects": "v4.3.0",
              "oxid-esales/developer-tools": "^v2.3.1",
              "oxid-esales/oxideshop-ide-helper": "^v6.1.1",
              "oxid-esales/twig-theme": "dev-b-7.0.x",
              "phpspec/prophecy-phpunit": "^v2.0.1",
              "phpstan/phpstan": "^1.9.14",
              "phpunit/phpunit": "^9.1.1",
              "squizlabs/php_codesniffer": "^3.5.4"
          },
          "autoload-dev":{
              "psr-4":{
                "OxidEsales\\EshopCommunity\\Tests\\":"./vendor/oxid-esales/oxideshop-ce/tests"
              }
          }
      }
  activate_modules: |
    oegdproptin
    oxps_usercentrics
    makaira_oxid-connect-essential
    ddoewysiwyg

runscript: &runscript
  matrix:
    script: |
      [
        "shop:~/unit.sh",
        "shop:~/compilation_integration.sh",
        "shop:~/compilation_codeception.sh",
        "shop:~/compilation_codeception_admin.sh",
        "gdpr:~/unit.sh",
        "gdpr:~/integration.sh",
        "gdpr:~/codeception.sh",
        "usercentrics:~/unit.sh",
        "usercentrics:~/integration.sh",
        "usercentrics:~/codeception.sh acceptance",
        "ddoe_wysiwyg:~/compilation_codeception.sh" 
      ]
  container:
    # {{ $selenium_options := "-e SELENIUM_SERVER_HOST=selenium -e BROWSER_NAME=chrome -e TEST_SUITE=/var/www/vendor/oxid-esales/oxideshop-ce/tests" }}
    # {{ $module_ids := "-e MODULE_IDS=oegdproptin,oxps_usercentrics,makaira_oxid-connect-essential,ddoewysiwyg" }}
    # {{ $integration_options := "-e INTEGRATION_OPTIONS=--exclude-group=exclude_from_compilation,exclude-from-compilation" }}
    options: '-e XDEBUG_MODE=coverage -e THEME_ID=apex {{ $module_ids }} {{ $selenium_options }} {{ $integration_options }} '
  composer:
    early: skip
  workdir: ''
  shop:
    path: 'vendor/oxid-esales/oxideshop-ce'
    workdir: 'vendor/oxid-esales/oxideshop-ce'
    custom_script: |
      cat >source/vendor/oxid-esales/oxideshop-ce/tests/scripts/compilation_codeception.sh <<EOF
      #!/bin/bash
      /var/www/vendor/bin/codecept build -c /var/www/vendor/oxid-esales/oxideshop-ce/tests/codeception.yml
      /var/www/vendor/bin/codecept run acceptance --bootstrap=/var/www/source/bootstrap.php  -c /var/www/vendor/oxid-esales/oxideshop-ce/tests/codeception.yml -x exclude_from_compilation -x flow_theme -x genericExport
      EOF
      chmod a+x source/vendor/oxid-esales/oxideshop-ce/tests/scripts/compilation_codeception.sh
      cat >source/vendor/oxid-esales/oxideshop-ce/tests/scripts/compilation_codeception_admin.sh <<EOF
      #!/bin/bash
      /var/www/vendor/bin/codecept build -c /var/www/vendor/oxid-esales/oxideshop-ce/tests/codeception.yml
      /var/www/vendor/bin/codecept run acceptanceAdmin --bootstrap=/var/www/source/bootstrap.php  -c /var/www/vendor/oxid-esales/oxideshop-ce/tests/codeception.yml -x exclude_from_compilation -x flow_theme -x genericExport
      EOF
      chmod a+x source/vendor/oxid-esales/oxideshop-ce/tests/scripts/compilation_codeception_admin.sh
      cat >source/vendor/oxid-esales/oxideshop-ce/tests/scripts/compilation_integration.sh <<EOF
      #!/bin/bash
      /var/www/vendor/bin/phpunit -c /var/www/vendor/oxid-esales/oxideshop-ce/phpunit.xml --testsuite=Integration --exclude-group exclude_from_compilation,exclude-from-compilation
      EOF
      chmod a+x source/vendor/oxid-esales/oxideshop-ce/tests/scripts/compilation_integration.sh
  gdpr:
    path: 'vendor/oxid-esales/gdpr-optin-module'
    custom_script: |
      perl -pi \
           -e 's#views/twig#views/apex#g;' \
           source/vendor/oxid-esales/gdpr-optin-module/tests/Codeception/acceptance.suite.yml
  usercentrics:
    path: 'vendor/oxid-professional-services/usercentrics'
    container:
  makaira:
    path: 'vendor/makaira/oxid-connect-essential'
  ddoe_wysiwyg:
    path: 'vendor/ddoe/wysiwyg-editor-module'
    custom_script: |
      cat >source/vendor/ddoe/wysiwyg-editor-module/tests/scripts/compilation_codeception.sh <<EOF
      #!/bin/bash
      export THEME_ID=twig
      /var/www/vendor/bin/codecept build -c /var/www/vendor/ddoe/wysiwyg-editor-module/tests/codeception.yml
      /var/www/vendor/bin/codecept run --bootstrap=/var/www/source/bootstrap.php  -c /var/www/vendor/ddoe/wysiwyg-editor-module/tests/codeception.yml       
      EOF
      chmod a+x source/vendor/ddoe/wysiwyg-editor-module/tests/scripts/compilation_codeception.sh

  medialibrary:
    path: 'vendor/oxid-esales/media-library-module'

sonarcloud:
  matrix:
    testplan: 'skip'

finish:
  slack_title: 'Metapackage CE (7.0 slim) on {{ .Github.Repository }} by {{ .Github.Actor }}'
