# {{ $ids := "apextheme" }}ids: {{ print $ids }}
# {{ $org := "oxid-esales" }}organisation: {{ print $org }}
# {{ $name := "apex-theme" }}name: {{ print $name }}
styles:
  title: '{{ print $name }}'
  path: '{{ print $ids }}'
  module_ids: '{{ print $ids }}'
