# {{ $ids := "ddoewysiwyg" }}ids: {{ print $ids }}
# {{ $org := "ddoe" }}organisation: {{ print $org }}
# {{ $name := "wysiwyg-editor-module" }}name: {{ print $name }}
codeception:
  title: '{{ print $name }}'
  container:
    options: '-e SELENIUM_SERVER_HOST=selenium -e BROWSER_NAME=chrome -e XDEBUG_MODE=coverage -e THEME_ID=twid'
  composer:
    transform: |
      {
        "require":     {
            "oxid-esales/twig-theme": "dev-b-7.0.x"
        }
      }
  configuration: '/var/www/vendor/{{ print $org }}/{{ print $name }}/tests/codeception.yml'
  additional_options: '--coverage-xml=/var/www/codeception_coverage_{{ print $ids }}.xml -g ddoe_wysiwyg'
  logfile:
    prefix: 'codeception-{{ print $name }}'
  output:
    prefix: 'codeception-acceptance-{{ print $name }}-artifacts'
    files: |
      docker-compose.yml
      source/composer.json
      source/composer.lock
      source/source/config.inc.php
      source/source/log/oxideshop.log
      data/php/logs/error_log.txt
      source/tests/Codeception/_output
      source/dev-packages/{{ print $ids }}/tests/Codeception/_output
      source/vendor/{{ print $org }}/{{ print $name }}/tests/Codeception/_output
      job_status*.txt
  coverage:
    prefix: 'coverage-reports-codeception-acceptance-{{ print $name }}'
    path: 'source/codeception_coverage_{{ print $ids }}.xml'
