# {{ $ids := "oedemodatainstaller" }}ids: {{ print $ids }}
# {{ $org := "oxid-esales" }}organisation: {{ print $org }}
# {{ $name := "oxideshop-demodata-installer" }}name: {{ print $name }}
phpunit:
  title: '{{ print $name }}-integration'
  container:
    options: ''
  configuration: '/var/www/vendor/{{ print $org }}/oxideshop-ce/phpunit.xml'  # ToDo: Replace this by a config from the module itself
  test: '/var/www/vendor/{{ print $org }}/{{ print $name }}/tests/Integration'
  additional_options: '--bootstrap /var/www/source/bootstrap.php'
  output:
    files: |
      source/composer.json
      source/integration_coverage_{{ print $ids }}.xml
      source/unit.cov
      source/source/log/oxideshop.log
      data/php/logs/error_log.txt
      files.txt
    prefix: 'phpunit-integration-{{ print $name }}-artifacts'
  logfile:
    prefix: 'phpunit-integration-{{ print $name }}'
  coverage:
    prefix: 'coverage-reports-phpunit-integration-{{ print $name }}'
    path: ''
